calendario/urls.py
# -*- coding: utf-8 -*-

from django.urls import path

from .views import CalendarioView, \
    EventoPredefinidoListView, EventoPredefinidoCreateView, EventoPredefinidoUpdateView, EventoPredefinidoDeleteView


urlpatterns = [
    path('calendario/', CalendarioView.as_view(), name="calendario"),
    path('calendario/predefinidos/', EventoPredefinidoListView.as_view(), name="evento_predefinido_lista"),
    path('calendario/predefinidos/nuevo/', EventoPredefinidoCreateView.as_view(), name="evento_predefinido_nuevo"),
    path('calendario/predefinidos/edita/<slug:pk>/', EventoPredefinidoUpdateView.as_view(),
         name="evento_predefinido_edita"),
    path('calendario/predefinidos/elimina/<slug:pk>/', EventoPredefinidoDeleteView.as_view(),
         name="evento_predefinido_elimina"),
]

django_calendario/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('calendario.urls')),
]

calendario/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
# from django.contrib.auth.models import User
# se cambia por, ya que el user puede estar personalizad:
from django.contrib.auth import get_user_model
User = get_user_model()



class ActualizaMixin(models.Model):
    creado = models.DateTimeField(_('Creado'), editable=False)
    modificado = models.DateTimeField(_('Actualizado'))

    def save(self, *args, **kwargs):
        if not self.id:
            self.creado = timezone.now()
        self.modificado = timezone.now()
        return super(ActualizaMixin, self).save(*args, **kwargs)

    class Meta:
        abstract = True


class AgendaEventoColor(ActualizaMixin):
    usuario = models.ForeignKey(User, verbose_name=_('User'), on_delete=models.CASCADE)
    color = models.CharField(verbose_name=_('Color'), max_length=7)

    class Meta:
        verbose_name = _('Agenda evento color')
        verbose_name_plural = _('Agenda evento colores')

    def __str__(self):
        return self.color


class AgendaEvento(ActualizaMixin):
    usuario = models.ForeignKey(User, verbose_name=_('User'), on_delete=models.CASCADE)
    color = models.ForeignKey(AgendaEventoColor, verbose_name=_('Color'), on_delete=models.CASCADE)
    inicio = models.DateTimeField(verbose_name=_('Inicio evento'), db_index=True)
    fin = models.DateTimeField(verbose_name=_('Fin evento'), db_index=True)
    titulo = models.CharField(verbose_name=_('Título'), max_length=250)
    dia_completo = models.BooleanField(verbose_name=_('Todo el día'), default=True)
    aviso_email = models.BooleanField(verbose_name=_('Avisar con email'), default=False)
    aviso_movil = models.BooleanField(verbose_name=_('Avisar con móvil'), default=False)
    email_enviado = models.DateTimeField(verbose_name=_('Email enviado'), null=True, blank=True)
    movil_enviado = models.DateTimeField(verbose_name=_('Móvil enviado'), null=True, blank=True)
    inicio_enviado = models.DateTimeField(verbose_name=_('Inicio enviado'), null=True, blank=True)

    class Meta:
        verbose_name = _('Agenda evento')
        verbose_name_plural = _('Agenda eventos')

    def __str__(self):
        return self.titulo


class AgendaEventoPredefinido(ActualizaMixin):
    usuario = models.ForeignKey(User, verbose_name=_('User'), on_delete=models.CASCADE)
    color = models.ForeignKey(AgendaEventoColor, verbose_name=_('Color'), on_delete=models.CASCADE)
    inicio = models.CharField(verbose_name=_('Hora inicio'), max_length=5, default='00:00')
    duracion = models.PositiveIntegerField(verbose_name=_('Minutos duración'), default=0)
    titulo = models.CharField(verbose_name=_('Título'), max_length=250)
    aviso_email = models.BooleanField(verbose_name=_('Avisar con email'), default=False)
    aviso_movil = models.BooleanField(verbose_name=_('Avisar con móvil'), default=False)

    class Meta:
        verbose_name = _('Agenda evento predefinido')
        verbose_name_plural = _('Agenda eventos predefinidos')

    def __str__(self):
        return self.titulo

    @property
    def horas(self):
        minutos = self.duracion
        horas = int(minutos / 60)
        minutos -= horas * 60
        return f'{str(horas).zfill(2)}:{str(minutos).zfill(2)}'

    @property
    def duracion_txt(self):
        minutos = self.duracion
        dias = int(minutos / 60 / 24)
        minutos -= dias * 60 * 24
        horas = int(minutos / 60)
        minutos -= horas * 60
        if dias:
            if dias > 1:
                return f'{dias} {_("Días")} {str(horas).zfill(2)}:{str(minutos).zfill(2)}'
            else:
                return f'1 {_("Día")} {str(horas).zfill(2)}:{str(minutos).zfill(2)}'
        else:
            return f'{str(horas).zfill(2)}:{str(minutos).zfill(2)}'


# https://docs.djangoproject.com/en/dev/topics/auth/customizing/#extending-the-existing-user-model
class Fcm(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=400, null=True, blank=True)

    def __str__(self):
        return self.token

calendario/forms/eventoPredefinidoForm.py
# -*- coding: utf-8 -*-

import json
from django import forms
from django.urls import reverse
from calendario.models import AgendaEventoPredefinido
from django.utils.translation import gettext_lazy as _


class Custom(forms.ChoiceField):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def validate(self, value):
        return value


class EventoPedefinidoForm(forms.ModelForm):
    data = forms.CharField(required=False, widget=forms.TextInput(attrs={"style": "display:none;"}))
    dias = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}),
                              label=_('Días'))
    minutos = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}),
                                 label=_('Minutos'))
    horas = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}),
                               label=_('Horas'))
    color = Custom(required=True, widget=forms.Select(attrs={'class': 'form-control color-select2',
                                                             'placeholder': _('Seleccione un color')}),
                   label=_('Color'),
                   help_text=_("Elija o añada un color en hexadecimal."))

    class Meta:
        model = AgendaEventoPredefinido
        fields = ('titulo', 'inicio', 'aviso_email', 'aviso_movil')
        labels = {
        }
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'inicio': forms.TextInput(attrs={'class': 'form-control', 'aria-describedby': 'inicio'}),
            'aviso_email': forms.CheckboxInput(attrs={'class': 'custom-control-input'}),
            'aviso_movil': forms.CheckboxInput(attrs={'class': 'custom-control-input'}),
        }
        required = ('titulo', )

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        object = kwargs.pop('object')
        super().__init__(*args, **kwargs)

        data_url = reverse('calendario')
        self.fields['color'].widget.attrs.update({'data-url': data_url})

        data = {
            'color': [[object.color.id, object.color.color]] if object else '',
        }
        self.fields['data'].initial = json.dumps(data)

        if object:
            minutos = object.duracion
            dias = int(minutos / 60 / 24)
            minutos -= dias * 60 * 24
            horas = int(minutos / 60)
            minutos -= horas * 60
            self.fields['dias'].initial = dias
            self.fields['horas'].initial = horas
            self.fields['minutos'].initial = minutos

    def clean(self):
        cleaned_data = super().clean()
        color = cleaned_data.get('color')
        if not color:
            self.add_error('color', _('Valor requerido'))

calendario/templates/calendario/predefinido/editar.html
{% extends 'calendario/base.html' %}
{% load static %}
{% load i18n %}

{% block titlehead %}
    {% trans 'Predefinido' %}
{% endblock titlehead %}

{% block content %}
    <div class='row'>
        <div class='col-md-12'>
            <form action='' method='post' enctype='multipart/form-data' role='form' id='formulario'>
                {% csrf_token %}
                {{ form.data }}
                <div class='card'>
                    <div class='card-header'>
                        <h3 class='panel-title text-secondary'>
                            {% if create_view %}
                                {% trans 'Nuevo Evento Predefinido' %}
                            {% else %}
                                {% trans 'Modificar Evento Predefinido' %}
                            {% endif %}
                        </h3>
                    </div>
                    <div class='card-body'>
                        <div class='form-row'>
                            <div class='form-group col-md-6'>
                                {{ form.titulo.errors }}
                                <label for={{form.titulo.auto_id}} class='control-label'>
                                    {{ form.titulo.label }}
                                    {% if form.titulo.field.required %}<span class='required_fields'>*</span>{% endif %}
                                </label>
                                {{ form.titulo }}
                                {% if form.titulo.help_text %}
                                <p><small class='text-secondary'>{{ form.titulo.help_text|safe }}</small></p>
                                {% endif %}
                            </div>
                            <div class='form-group col-md-4'>
                                {{ form.color.errors }}
                                <label for={{form.color.auto_id}} class='control-label'>
                                    {{ form.color.label }}
                                    {% if form.color.field.required %}<span class='required_fields'>*</span>{% endif %}
                                </label>
                                {{ form.color }}
                                {% if form.color.help_text %}
                                    <p><small class='text-secondary'>{{ form.color.help_text|safe }}</small></p>
                                {% endif %}
                            </div>
                            <div class='form-group  col-md-2'>
                                    <label for='inicio' class='control-label'>
                                        {{ form.inicio.label }}
                                    </label>
                                <div class='input-group'>
                                    {{ form.inicio }}
                                    <div class='input-group-append'>
                                        <span class='input-group-text' id='inicio'><i class='fa fa-clock-o'></i></span>
                                    </div>
                                </div>
                            </div>
                            <div class='col-md-12'>
                                <div class='row'>
                                    <div class='col-md-1'>
                                        <label class='col-form-label'>{% trans 'Duración' %}:</label>
                                    </div>
                                    <div class='col-md-2'>
                                        {{ form.dias }}
                                        <small class='text-secondary'>Días</small>
                                    </div>
                                    <div class='col-md-2'>
                                        {{ form.horas }}
                                        <small class='text-secondary'>Horas</small>
                                    </div>
                                    <div class='col-md-2'>
                                        {{ form.minutos }}
                                        <small class='text-secondary'>Minutos</small>
                                    </div>
                                    <div class='col-md-2 offset-md-1' style='margin-top:10px'>
                                        <div class="custom-control custom-checkbox">
                                            {{ form.aviso_email }}
                                            <label class="custom-control-label" for="{{form.aviso_email.auto_id}}">
                                                {{ form.aviso_email.label }}
                                            </label>
                                        </div>
                                    </div>
                                    <div class='col-md-2' style='margin-top:10px'>
                                        <div class="custom-control custom-checkbox">
                                            {{ form.aviso_movil }}
                                            <label class="custom-control-label" for="{{form.aviso_movil.auto_id}}">
                                                {{ form.aviso_movil.label }}
                                            </label>
                                        </div>
                                    </div>
                                 </div>
                            </div>
                        </div>
                    </div>
                    <div class='card-footer'>
                        <a class='btn btn-danger' href='{% url "evento_predefinido_lista" %}'>
                            <i class='fa fa-ban'></i>
                            {% trans 'Cancelar' %}
                        </a>
                        <button type='submit' class='btn btn-success'>
                            <i class='fa fa-check'></i>
                            {% trans 'Guardar' %}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
	<script>
        {% if create_view %}
            iniciaTimepicker($('#id_inicio'), new Date());
        {% else %}
            var hora = $('#id_inicio').val(),
                date = moment('2022-10-10 ' + hora , 'YYYY-MM-DD HH:mm').toDate();
            iniciaTimepicker($('#id_inicio'), date);
        {% endif %}

        var valores = $('#id_data').val();
        if (valores.length > 0) {
            data = JSON.parse(valores);
            select2_set_value($('#id_color'), data.color);
        }
	</script>
{% endblock scripts %}

calendario/templates/calendario/predefinido/eliminar.html
{% extends 'calendario/base.html' %}
{% load i18n %}
{% load static %}
{% block titlehead %}{% trans 'Eliminar Libro' %}{% endblock titlehead %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <form action="" method="post" enctype="multipart/form-data" role="form" id="formulario">
                {% csrf_token %}
                <div class="card">
                    <div class="card-header">
                        <h3 class="panel-title text-secondary">{% trans 'Borrar Evento Predefinido' %}</h3>
                    </div>
                    <div class="card-body">
                        <div class="alert alert-warning">
                            <strong>{% trans 'Atención!' %}</strong> {% trans 'Va a proceder a borrar un Evento Predefinido' %}.
                        </div>
                        <p>{% trans '¿Seguro que desea eliminar el evento predefinido' %}?: <b>{{ agendaeventopredefinido }}</b></p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-danger" href="{% url 'evento_predefinido_lista' %}">
                            <i class="fa fa-ban"></i>
                            {% trans 'Cancelar' %}
                        </a>
                        <button type="submit" class="btn btn-success">
                            <i class="fa fa-check"></i>
                            {% trans 'Aceptar' %}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

calendario/templates/calendario/predefinido/lista.html
{% extends 'calendario/base.html' %}
{% load i18n %}
{% load static %}
{% block titlehead %}{% trans 'Predefinido' %}{% endblock titlehead %}

{% block styles %}
    {{ block.super }}
    <style>
        .th-minimo {
            width:90px;
        }
        .accion {
            margin-left: 18px;
        }
        .color-cuadro {
            border:1px solid black;
            margin-top:0px;
            margin-left:0px;
            height: 20px;
            width: 80px;
        }
    </style>
{% endblock styles %}

{% block content %}
	<div id="toolbar">
        <a class="btn btn-primary" href="{% url 'evento_predefinido_nuevo' %}">
            <i class='fa fa-plus-circle'></i>
            {% trans 'Crear evento predefinido' %}
        </a>
	</div>
    <div class="container-fluid" style="padding:.75rem;">
        <h3 class="text-secondary">Eventos Predefinidos</h3>
        <div class="dataTable_wrapper">
            <table width="100%"
                data-toolbar="#toolbar"
                id="id_predefinido"
                class="table table-striped table-bordered table-hover"
                data-toggle="table"
                data-search="true"
                data-show-fullscreen="false"
                data-search-on-enter-key="false"
                data-search-time-out="1000"
                data-pagination="true"
                data-page-size="15"
                data-page-list="[15, 25, 100, 500, Todo]"
                data-locale="es-SP"
                data-cookie="true"
                data-cookie-id-table="Notas"
                data-cookie-expire="12m"
                data-cookie-path="/"
                data-id-field="id"
                data-sortable="true"
                data-resizable="false"
                >
                <thead>
                    <tr>
                        <th data-visible="false" data-field="id"></th>
                        <th data-field="nombre" data-sortable="true">{% trans 'Título' %}</th>
                        <th class="th-minimo" data-field="inicio" data-sortable="true">{% trans 'Inicio' %}</th>
                        <th data-field="duracion_txt" data-sortable="true">{% trans 'Duración' %}</th>
                        <th class="text-center" data-field="aviso_email" data-sortable="true" data-formatter="boolFormat">{% trans 'Aviso con Email' %}</th>
                        <th class="text-center" data-field="aviso_movil" data-sortable="true" data-formatter="boolFormat">{% trans 'Aviso con Móvil' %}</th>
                        <th class="text-center th-minimo" data-field="color" data-sortable="true">{% trans 'Color' %}</th>
                        <th class="text-center th-minimo" data-sortable="false">{% trans 'Acciones' %}</th>
                    </tr>
                </thead>
                {% for evt in agendaeventopredefinido_list %}
                    <tr>
                        <td>{{ evt.id }}</td>
                        <td>{{ evt.titulo }}</td>
                        <td>{{ evt.inicio }}</td>
                        <td>{{ evt.duracion_txt }} {% trans 'Horas' %}</td>
                        <td>{{ evt.aviso_email }}</td>
                        <td>{{ evt.aviso_movil }}</td>
                        <td><div class="color-cuadro" style='background-color:{{evt.color}};'></div></td>
                        <td>
                            <a href="{% url 'evento_predefinido_elimina' evt.id %}" class="text-danger" role="button" title="{% trans 'Eliminar evento predefinido' %}"><span class="fa fw fa-trash"></span></a>
                            <a href="{% url 'evento_predefinido_edita' evt.id %}" class="text-primary accion" role="button" title="{% trans 'Editar evento predefinido' %}"><span class="fa fw fa-pencil"></span></a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
        </div>
        <div class="col-4 d-flex justify-content-center">
            <a type="button" class="btn btn-outline-secondary min-width-150" href="{% url 'calendario' %}">
                <i class="fa fa-arrow-circle-left"></i>
                {% trans 'Volver al calendario' %}
            </a>
        </div>
        <div class="col-4">
        </div>
    </div>
{% endblock content %}

{% block scripts %}
	<script>
        function boolFormat(value, row, index) {
            if (value == 'True')
                return '<img src={% static "admin/img/icon-yes.svg" %} alt="True"/>';
            return '<img src={% static "admin/img/icon-no.svg" %} alt="False"/>';
        }

        function accionFormatter(value, row, index) {
            var eliminar = "{% url 'evento_predefinido_edita' 0 %}".replace('0', row.id);
            var editar = "{% url 'evento_predefinido_elimina' 0 %}".replace('0', row.id);
            return `
                <a href="${eliminar}" class="text-danger accion" role="button" title="{% trans 'Eliminar evento' %}"><span class="fa fw fa-trash"></span></a>
                <a href="${editar}" class="text-primary accion" role="button" title="{% trans 'Editar evento' %}"><span class="fa fw fa-pencil"></span></a>
            `;
        }

        $(document).on('click','.clear_search',function(){
            $('#id_predefinido').bootstrapTable('resetSearch');
        });

		$(function() {
			$('#id_predefinido').bootstrapTable('refresh');
            $('.search').find('input[type=search]').each(function(e) {
                $(this).parent().prepend('<a href="#" style="padding-top:6px;margin-right:10px" class="close clear_search" data-dismiss="alert">×</a>');
            });
			$('.container-fluid').removeAttr('hidden');
		});
	</script>
{% endblock scripts %}